# Example Gitaly configuration file
# Documentation lives at https://docs.gitlab.com/ee/administration/gitaly/ and
# https://docs.gitlab.com/ee//administration/gitaly/reference

socket_path = "{{GITALY_SOCKET_PATH}}"

# The directory where Gitaly's executables are stored
bin_dir = "{{GITLAB_GITALY_INSTALL_DIR}}"

# Git settings
[git]
bin_path = "/usr/bin/git"
catfile_cache_size = 100

[[storage]]
name = "default"
path = "{{GITLAB_REPOS_DIR}}"

[logging]
dir = "{{GITLAB_LOG_DIR}}"

[gitaly-ruby]
# The directory where gitaly-ruby is installed
dir = "{{GITLAB_GITALY_INSTALL_DIR}}/ruby"

[gitlab-shell]
# The directory where gitlab-shell is installed
dir = "{{GITLAB_SHELL_INSTALL_DIR}}"

[hooks]
custom_hooks_dir = "/home/git/custom_hooks"

[gitlab]
secret_file = "{{GITLAB_INSTALL_DIR}}/.gitlab_shell_secret"
url = "http://localhost:8181"

[gitlab.http-settings]
self_signed_cert = false
